# Generated by Django 4.2.4 on 2023-08-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='auth_code',
            field=models.IntegerField(max_length=4, null=True, verbose_name='Код авторизации'),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(max_length=6, null=True, verbose_name='Инвайт-код'),
        ),
    ]
