# Generated by Django 4.2.4 on 2023-08-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_about_remove_user_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_code',
            field=models.IntegerField(null=True, verbose_name='Код авторизации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(max_length=6, null=True, unique=True, verbose_name='Инвайт-код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(unique=True, verbose_name='Мобильный телефон'),
        ),
    ]
