# Generated by Django 4.2.4 on 2023-08-07 08:20

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_auth_code_alter_user_invite_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activated_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Использованный инвайт-код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Мобильный телефон'),
        ),
    ]
