# Generated by Django 4.2.4 on 2023-08-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_activated_code_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_code',
            field=models.CharField(null=True, verbose_name='Код авторизации'),
        ),
    ]
