# Generated by Django 4.2.4 on 2023-08-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_auth_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activated_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Использованный инвайт-код'),
        ),
    ]
