services:

  # Django
  web:
    build: .
    volumes:
      - .:/service
      - static_volume:/service/static
      - media_volume:/service/media
    ports:
      - 8000:8000
    env_file:
      - web.env
    image: app:django
    container_name: django_service
    command: python manage.py runserver 0.0.0.0:8000


  # PostgreSQL
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - web.env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    container_name: django_service_db


volumes:
  db:
    driver: local

  static_volume:
  media_volume: